#!/bin/bash

# CI script to build go code

set -o errexit
set -o nounset
set -o pipefail

# cd to the repo root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "${REPO_ROOT}"

CGO_ENABLED=0 go build ./...
