#!/bin/bash

# CI script to run addlicense
set -o errexit
set -o nounset
set -o pipefail

# cd to the repo root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "${REPO_ROOT}"

go run github.com/google/addlicense@latest -f dev/boilerplate.txt .
