#!/bin/bash

# CI script to run all the lint commands

set -o errexit
set -o nounset
set -o pipefail

# cd to the repo root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "${REPO_ROOT}"

dev/lint-go
dev/lint-shell
