#!/bin/bash

# script for the "build" presubmit

set -o errexit
set -o nounset
set -o pipefail

# cd to the repo root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "${REPO_ROOT}"

# Install preferred golang version into PATH
. dev/helpers/ci-install-golang.sh

dev/build
